name: "Docker Build and Push"

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

jobs:
  build-image:

    runs-on: ubuntu-latest
    
    name: Build and Upload Docker Image
    
    steps:
    - uses: actions/checkout@v3

    - name: Extract metadata - Stable
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: la1tv/website-frontend
        # type=match,pattern=(.*) is untested and will need testing
        tags: |
            type=raw,value=stable
            type=match,pattern=(.*)

    - name: Extract metadata - Beta
      if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: la1tv/website-frontend
        tags: |
            type=raw,value=beta

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}